@startuml buffdata_factory_relation
title BuffData / Factory / Nodeの関係
hide empty member

class BuffData

class BuffFactory

class Buff

class BuffNode

BuffData .right.> BuffFactory : 材料の投入
BuffFactory .right.> Buff : バフを生成
BuffNode <.. BuffData
BuffNode <.. BuffFactory

note bottom of BuffFactory
  バフを生成するジェネレータ
end note
note top of BuffNode
  材料とジェネレータをまとめて設定するもの
end note
note bottom of Buff
  攻撃力UP・毒状態など
  振る舞いをもたらす
end note
@enduml