@startuml invector_attack_logic
title プレイヤーの装備による攻撃方法決定

actor Player
participant vMeleeCombatInput
participant vMeleeManager
participant Animator

Player -> vMeleeCombatInput++ : 攻撃ボタン押下
vMeleeCombatInput -> vMeleeCombatInput++ : TriggerWeakAttack()
vMeleeCombatInput -> vMeleeManager++ : GetAttackID()

alt 武器がOnlyDefense以外
    vMeleeManager --> vMeleeCombatInput : rightWeapon.attackID
else
    return 0
end
vMeleeCombatInput -> Animator : SetInteger("attackID", attackID)
vMeleeCombatInput -> Animator++ : SetTrigger("weakAttack")
Animator --> Player-- : 攻撃アニメーション
return void

@enduml