@startuml status_effect_sequence
title 状態異常受付側のシーケンス図

actor Enemy
participant EffectReceiver
participant EffectRegistData
participant EffectBehaviour

-> Enemy++ : 被弾
Enemy -> EffectReceiver++ : ApplyEffect(damage)
EffectReceiver -> EffectReceiver++ : リスト内からtypeに一致するRegistData検索
return 一致したRegistData
EffectReceiver -> EffectRegistData--++ : 蓄積値を加算
EffectRegistData -> EffectRegistData : 蓄積値が閾値に達したか確認
opt 蓄積値が最大値以上
    EffectRegistData -> EffectBehaviour** : Instantiate()
    EffectRegistData -> EffectBehaviour++ : Invoke()
    EffectBehaviour --> Enemy : ステータスを変更
    return appliedにgameObject代入
    deactivate EffectRegistData
    
    EffectBehaviour -> EffectBehaviour++ : 時間計測
    
    opt 持続時間を超過
        EffectBehaviour --> EffectRegistData++ : OnRemoved.Invoke()
        EffectRegistData -> EffectBehaviour : Remove()
        EffectBehaviour --> Enemy : ステータスを変更
        EffectRegistData -> EffectBehaviour!! : Destroy()
        EffectRegistData -> EffectRegistData-- : 蓄積０
    end
end

@enduml