@startuml status_effect_attacker
title 状態異常攻撃側のシーケンス図

actor Player
participant vMeleeWeapon
participant EffectGiver
participant EffectDamage
actor Enemy
participant EffectReceiver

opt エンチャントアイテムなど使用時
Player -> vMeleeWeapon : AddComponent<EffectGiver>
end
== 攻撃ヒット ==
vMeleeWeapon -> vMeleeWeapon++ : onDamageHit.Invoke()
vMeleeWeapon -> EffectGiver--++ : ApplyEffect(hitinfo.collider)
EffectGiver -> EffectDamage** : new(異常タイプ,蓄積値,効果量,持続時間)
EffectGiver -> Enemy--++ : ApplyEffect(damage)
Enemy -> EffectReceiver++ : GetComponentInChildren
return receiver
Enemy -> EffectReceiver : ApplyEffect(damage)
@enduml